// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXNW1OjZtI-zjU9hF5saIrhfClFpoOKfU',
    appId: '1:185474246383:web:539ecb6c75971728181d1a',
    messagingSenderId: '185474246383',
    projectId: 'etext-85ef6',
    authDomain: 'etext-85ef6.firebaseapp.com',
    storageBucket: 'etext-85ef6.firebasestorage.app',
    measurementId: 'G-HLR80ZSHEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKjtZczXbGRMlwJsqKBmKXs0fA9DTCj1Y',
    appId: '1:185474246383:android:90e85743cafa0532181d1a',
    messagingSenderId: '185474246383',
    projectId: 'etext-85ef6',
    storageBucket: 'etext-85ef6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPVcrX9SHJmQGKG2EdIdO6Fqa0040okhE',
    appId: '1:185474246383:ios:d1307657b4f73c33181d1a',
    messagingSenderId: '185474246383',
    projectId: 'etext-85ef6',
    storageBucket: 'etext-85ef6.firebasestorage.app',
    iosBundleId: 'com.example.etext',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPVcrX9SHJmQGKG2EdIdO6Fqa0040okhE',
    appId: '1:185474246383:ios:d1307657b4f73c33181d1a',
    messagingSenderId: '185474246383',
    projectId: 'etext-85ef6',
    storageBucket: 'etext-85ef6.firebasestorage.app',
    iosBundleId: 'com.example.etext',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXNW1OjZtI-zjU9hF5saIrhfClFpoOKfU',
    appId: '1:185474246383:web:956c1fd5179039e4181d1a',
    messagingSenderId: '185474246383',
    projectId: 'etext-85ef6',
    authDomain: 'etext-85ef6.firebaseapp.com',
    storageBucket: 'etext-85ef6.firebasestorage.app',
    measurementId: 'G-PEEYT95BHV',
  );
}
